name: 'Terraform'

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.7
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: List IAM Roles
      run: |
        aws iam list-roles --query 'Roles[].RoleName' --output text

    - name: Verify AWS credentials
      run: |
        aws sts get-caller-identity
        aws iam get-role --role-name ec2_role || echo "Role not found"
    
    - name: Check for existing IAM role
      run: |
        ROLE_NAME="ec2_role"
        if aws iam get-role --role-name $ROLE_NAME; then
          echo "IAM Role $ROLE_NAME already exists, skipping creation."
        else
          echo "IAM Role $ROLE_NAME does not exist, proceeding with creation."
        fi

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
      
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master'
      run: terraform apply -auto-approve
